document.addEventListener('DOMContentLoaded', () => {
    fetchStatusData();
    // Re-fetch every 5 minutes just in case they keep the tab open
    setInterval(fetchStatusData, 5 * 60 * 1000);
});

async function fetchStatusData() {
    try {
        // Fetch the raw JSON generated by GitHub Actions
        // Adding a cache buster to ensure fresh data
        const response = await fetch(`data/status.json?t=${new Date().getTime()}`);
        if (!response.ok) throw new Error('Network response was not ok');

        const data = await response.json();
        renderServices(data);
        updateGlobalStatus(data);
    } catch (error) {
        console.error('Failed to fetch status data:', error);
        showErrorState();
    }
}

function updateGlobalStatus(data) {
    const globalEl = document.getElementById('global-status');
    const textEl = globalEl.querySelector('.status-text');

    let allUp = true;
    let issuesCount = 0;

    Object.values(data).forEach(service => {
        if (service.status !== 'UP') {
            allUp = false;
            issuesCount++;
        }
    });

    globalEl.classList.remove('loading', 'all-up', 'issues');

    if (allUp) {
        globalEl.classList.add('all-up');
        textEl.textContent = 'All Systems Operational';
    } else {
        globalEl.classList.add('issues');
        textEl.textContent = `${issuesCount} System${issuesCount > 1 ? 's' : ''} Experiencing Issues`;
    }
}

function renderServices(data) {
    const grid = document.getElementById('services-grid');
    const template = document.getElementById('service-card-template');

    // Clear grid (removes skeletons)
    grid.innerHTML = '';

    // Convert object to array and sort (maybe put DOWN/DEGRADED first)
    const services = Object.entries(data).map(([name, info]) => ({ name, ...info }));
    services.sort((a, b) => {
        const order = { 'DOWN': 3, 'DEGRADED': 2, 'UP': 1 };
        return (order[b.status] || 0) - (order[a.status] || 0);
    });

    services.forEach((service, index) => {
        const clone = template.content.cloneNode(true);
        const link = clone.querySelector('.service-card-link');
        const card = clone.querySelector('.service-card');

        // Set link to official status page
        if (service.url) {
            link.href = service.url;
        } else {
            link.removeAttribute('target');
            link.style.cursor = 'default';
        }

        // Add animation delay for stagger effect
        card.style.animationDelay = `${index * 0.1}s`;

        // Set Status Theme
        card.setAttribute('data-status', service.status);

        // Populate Data
        clone.querySelector('.provider-name').textContent = service.name;
        clone.querySelector('.badge-text').textContent = service.status;
        clone.querySelector('.status-description').textContent = service.description || 'No additional details provided.';

        // Time Formatting
        const checkDate = new Date(service.lastChecked);
        clone.querySelector('.time-ago').textContent = timeSince(checkDate);
        clone.querySelector('.time-ago').title = checkDate.toLocaleString(); // Hover for full date

        grid.appendChild(clone);
    });
}

function showErrorState() {
    const grid = document.getElementById('services-grid');
    grid.innerHTML = '<div style="grid-column: 1 / -1; text-align: center; color: var(--color-down);">Failed to load status data. Please try again later.</div>';

    const globalEl = document.getElementById('global-status');
    globalEl.classList.remove('loading', 'all-up');
    globalEl.classList.add('issues');
    globalEl.querySelector('.status-text').textContent = 'System Outage';
}

function timeSince(date) {
    const seconds = Math.floor((new Date() - date) / 1000);
    let interval = seconds / 31536000;

    if (interval > 1) return Math.floor(interval) + " years ago";
    interval = seconds / 2592000;
    if (interval > 1) return Math.floor(interval) + " months ago";
    interval = seconds / 86400;
    if (interval > 1) return Math.floor(interval) + " days ago";
    interval = seconds / 3600;
    if (interval > 1) return Math.floor(interval) + " hours ago";
    interval = seconds / 60;
    if (interval > 1) return Math.floor(interval) + " minutes ago";
    return Math.floor(seconds) + " seconds ago";
}
